name: Tests + Annotations Report

on: push

jobs:
  test:
    name: Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # If we hit a bad cache for some reason, increment this
        # number to generate a new unique cache-key which will
        # cause a cache miss & rebuild on the next run
        cache_version: ["1"]
        otp: ["23"]
        elixir: ["1.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          experimental-otp: true
      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ matrix.cache_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix compile --warnings-as-errors
      - name: Static code quality checks
        run: |
          mix format --check-formatted
          mix credo
      - name: Run tests
        run: mix test
      - name: Run dialyzer
        run: mix dialyzer
      - name: Code Annotations Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: "reports/junit/*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
